/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Game {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  genre: string | null;
  id: Generated<string>;
  logo: string | null;
  name: string;
  organizationId: string;
  platforms: string[] | null;
  sdk: string | null;
  settings: Json | null;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
}

export interface GameApiKey {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  expiresAt: Timestamp | null;
  gameId: string;
  id: Generated<string>;
  keyHash: string;
  lastUsedAt: Timestamp | null;
  scopes: Generated<string[]>;
}

export interface Invitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Member {
  createdAt: Generated<Timestamp>;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: Generated<Timestamp>;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Player {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  gameId: string;
  id: string;
  image: string | null;
  isAnonymous: boolean | null;
  lastLoginAt: Timestamp | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface PlayerAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface PlayerSession {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  settings: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  game: Game;
  gameApiKey: GameApiKey;
  invitation: Invitation;
  member: Member;
  organization: Organization;
  player: Player;
  playerAccount: PlayerAccount;
  playerSession: PlayerSession;
  session: Session;
  user: User;
  verification: Verification;
}
