/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LayoutAuthedRouteImport } from './routes/_layout/_authed'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as LayoutAuthedIndexRouteImport } from './routes/_layout/_authed/index'
import { Route as ApiUserAvatarRouteImport } from './routes/api/user/avatar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutAuthedAccountRouteImport } from './routes/_layout/_authed/account'
import { Route as LayoutAuthedPlayersIndexRouteImport } from './routes/_layout/_authed/players/index'
import { Route as LayoutAuthedOrganizationsIndexRouteImport } from './routes/_layout/_authed/organizations/index'
import { Route as LayoutAuthedGamesIndexRouteImport } from './routes/_layout/_authed/games/index'
import { Route as ApiUserUserIdAvatarRouteImport } from './routes/api/user/$userId/avatar'
import { Route as ApiOrganizationOrganizationIdLogoRouteImport } from './routes/api/organization/$organizationId/logo'
import { Route as ApiGameGameIdLogoRouteImport } from './routes/api/game/$gameId/logo'
import { Route as LayoutAuthedOrganizationsOrganizationIdRouteImport } from './routes/_layout/_authed/organizations/$organizationId'
import { Route as AuthInvitationInvitationIdAcceptRouteImport } from './routes/_auth/invitation/$invitationId/accept'
import { Route as LayoutAuthedGamesGameIdIndexRouteImport } from './routes/_layout/_authed/games/$gameId/index'
import { Route as LayoutAuthedGamesGameIdPlayersIndexRouteImport } from './routes/_layout/_authed/games/$gameId/players/index'
import { Route as LayoutAuthedGamesGameIdPlayersPlayerIdRouteImport } from './routes/_layout/_authed/games/$gameId/players/$playerId'
import { Route as ApiV1GameGameIdPlayerPlayerIdIndexRouteImport } from './routes/api/v1/game/$gameId/player/$playerId/index'
import { Route as ApiV1GameGameIdPlayerSignUpEmailRouteImport } from './routes/api/v1/game/$gameId/player/sign-up/email'
import { Route as ApiV1GameGameIdPlayerSignInEmailRouteImport } from './routes/api/v1/game/$gameId/player/sign-in/email'
import { Route as ApiV1GameGameIdPlayerSignInAnonymouslyRouteImport } from './routes/api/v1/game/$gameId/player/sign-in/anonymously'
import { Route as ApiV1GameGameIdPlayerSessionRevokeRouteImport } from './routes/api/v1/game/$gameId/player/session/revoke'
import { Route as ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRouteImport } from './routes/api/v1/game/$gameId/player/$playerId/send-verification-email'
import { Route as ApiV1GameGameIdPlayerPlayerIdResetPasswordRouteImport } from './routes/api/v1/game/$gameId/player/$playerId/reset-password'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedRoute = LayoutAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutAuthedIndexRoute = LayoutAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const ApiUserAvatarRoute = ApiUserAvatarRouteImport.update({
  id: '/api/user/avatar',
  path: '/api/user/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedAccountRoute = LayoutAuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const LayoutAuthedPlayersIndexRoute =
  LayoutAuthedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedOrganizationsIndexRoute =
  LayoutAuthedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedGamesIndexRoute = LayoutAuthedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const ApiUserUserIdAvatarRoute = ApiUserUserIdAvatarRouteImport.update({
  id: '/api/user/$userId/avatar',
  path: '/api/user/$userId/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationOrganizationIdLogoRoute =
  ApiOrganizationOrganizationIdLogoRouteImport.update({
    id: '/api/organization/$organizationId/logo',
    path: '/api/organization/$organizationId/logo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGameGameIdLogoRoute = ApiGameGameIdLogoRouteImport.update({
  id: '/api/game/$gameId/logo',
  path: '/api/game/$gameId/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedOrganizationsOrganizationIdRoute =
  LayoutAuthedOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const AuthInvitationInvitationIdAcceptRoute =
  AuthInvitationInvitationIdAcceptRouteImport.update({
    id: '/invitation/$invitationId/accept',
    path: '/invitation/$invitationId/accept',
    getParentRoute: () => AuthRoute,
  } as any)
const LayoutAuthedGamesGameIdIndexRoute =
  LayoutAuthedGamesGameIdIndexRouteImport.update({
    id: '/games/$gameId/',
    path: '/games/$gameId/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedGamesGameIdPlayersIndexRoute =
  LayoutAuthedGamesGameIdPlayersIndexRouteImport.update({
    id: '/games/$gameId/players/',
    path: '/games/$gameId/players/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedGamesGameIdPlayersPlayerIdRoute =
  LayoutAuthedGamesGameIdPlayersPlayerIdRouteImport.update({
    id: '/games/$gameId/players/$playerId',
    path: '/games/$gameId/players/$playerId',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const ApiV1GameGameIdPlayerPlayerIdIndexRoute =
  ApiV1GameGameIdPlayerPlayerIdIndexRouteImport.update({
    id: '/api/v1/game/$gameId/player/$playerId/',
    path: '/api/v1/game/$gameId/player/$playerId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameGameIdPlayerSignUpEmailRoute =
  ApiV1GameGameIdPlayerSignUpEmailRouteImport.update({
    id: '/api/v1/game/$gameId/player/sign-up/email',
    path: '/api/v1/game/$gameId/player/sign-up/email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameGameIdPlayerSignInEmailRoute =
  ApiV1GameGameIdPlayerSignInEmailRouteImport.update({
    id: '/api/v1/game/$gameId/player/sign-in/email',
    path: '/api/v1/game/$gameId/player/sign-in/email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameGameIdPlayerSignInAnonymouslyRoute =
  ApiV1GameGameIdPlayerSignInAnonymouslyRouteImport.update({
    id: '/api/v1/game/$gameId/player/sign-in/anonymously',
    path: '/api/v1/game/$gameId/player/sign-in/anonymously',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameGameIdPlayerSessionRevokeRoute =
  ApiV1GameGameIdPlayerSessionRevokeRouteImport.update({
    id: '/api/v1/game/$gameId/player/session/revoke',
    path: '/api/v1/game/$gameId/player/session/revoke',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRoute =
  ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRouteImport.update({
    id: '/api/v1/game/$gameId/player/$playerId/send-verification-email',
    path: '/api/v1/game/$gameId/player/$playerId/send-verification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GameGameIdPlayerPlayerIdResetPasswordRoute =
  ApiV1GameGameIdPlayerPlayerIdResetPasswordRouteImport.update({
    id: '/api/v1/game/$gameId/player/$playerId/reset-password',
    path: '/api/v1/game/$gameId/player/$playerId/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/account': typeof LayoutAuthedAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/avatar': typeof ApiUserAvatarRoute
  '/': typeof LayoutAuthedIndexRoute
  '/invitation/$invitationId/accept': typeof AuthInvitationInvitationIdAcceptRoute
  '/organizations/$organizationId': typeof LayoutAuthedOrganizationsOrganizationIdRoute
  '/api/game/$gameId/logo': typeof ApiGameGameIdLogoRoute
  '/api/organization/$organizationId/logo': typeof ApiOrganizationOrganizationIdLogoRoute
  '/api/user/$userId/avatar': typeof ApiUserUserIdAvatarRoute
  '/games': typeof LayoutAuthedGamesIndexRoute
  '/organizations': typeof LayoutAuthedOrganizationsIndexRoute
  '/players': typeof LayoutAuthedPlayersIndexRoute
  '/games/$gameId': typeof LayoutAuthedGamesGameIdIndexRoute
  '/games/$gameId/players/$playerId': typeof LayoutAuthedGamesGameIdPlayersPlayerIdRoute
  '/games/$gameId/players': typeof LayoutAuthedGamesGameIdPlayersIndexRoute
  '/api/v1/game/$gameId/player/$playerId/reset-password': typeof ApiV1GameGameIdPlayerPlayerIdResetPasswordRoute
  '/api/v1/game/$gameId/player/$playerId/send-verification-email': typeof ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRoute
  '/api/v1/game/$gameId/player/session/revoke': typeof ApiV1GameGameIdPlayerSessionRevokeRoute
  '/api/v1/game/$gameId/player/sign-in/anonymously': typeof ApiV1GameGameIdPlayerSignInAnonymouslyRoute
  '/api/v1/game/$gameId/player/sign-in/email': typeof ApiV1GameGameIdPlayerSignInEmailRoute
  '/api/v1/game/$gameId/player/sign-up/email': typeof ApiV1GameGameIdPlayerSignUpEmailRoute
  '/api/v1/game/$gameId/player/$playerId': typeof ApiV1GameGameIdPlayerPlayerIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/account': typeof LayoutAuthedAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/avatar': typeof ApiUserAvatarRoute
  '/': typeof LayoutAuthedIndexRoute
  '/invitation/$invitationId/accept': typeof AuthInvitationInvitationIdAcceptRoute
  '/organizations/$organizationId': typeof LayoutAuthedOrganizationsOrganizationIdRoute
  '/api/game/$gameId/logo': typeof ApiGameGameIdLogoRoute
  '/api/organization/$organizationId/logo': typeof ApiOrganizationOrganizationIdLogoRoute
  '/api/user/$userId/avatar': typeof ApiUserUserIdAvatarRoute
  '/games': typeof LayoutAuthedGamesIndexRoute
  '/organizations': typeof LayoutAuthedOrganizationsIndexRoute
  '/players': typeof LayoutAuthedPlayersIndexRoute
  '/games/$gameId': typeof LayoutAuthedGamesGameIdIndexRoute
  '/games/$gameId/players/$playerId': typeof LayoutAuthedGamesGameIdPlayersPlayerIdRoute
  '/games/$gameId/players': typeof LayoutAuthedGamesGameIdPlayersIndexRoute
  '/api/v1/game/$gameId/player/$playerId/reset-password': typeof ApiV1GameGameIdPlayerPlayerIdResetPasswordRoute
  '/api/v1/game/$gameId/player/$playerId/send-verification-email': typeof ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRoute
  '/api/v1/game/$gameId/player/session/revoke': typeof ApiV1GameGameIdPlayerSessionRevokeRoute
  '/api/v1/game/$gameId/player/sign-in/anonymously': typeof ApiV1GameGameIdPlayerSignInAnonymouslyRoute
  '/api/v1/game/$gameId/player/sign-in/email': typeof ApiV1GameGameIdPlayerSignInEmailRoute
  '/api/v1/game/$gameId/player/sign-up/email': typeof ApiV1GameGameIdPlayerSignUpEmailRoute
  '/api/v1/game/$gameId/player/$playerId': typeof ApiV1GameGameIdPlayerPlayerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_layout/_authed': typeof LayoutAuthedRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_layout/_authed/account': typeof LayoutAuthedAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/avatar': typeof ApiUserAvatarRoute
  '/_layout/_authed/': typeof LayoutAuthedIndexRoute
  '/_auth/invitation/$invitationId/accept': typeof AuthInvitationInvitationIdAcceptRoute
  '/_layout/_authed/organizations/$organizationId': typeof LayoutAuthedOrganizationsOrganizationIdRoute
  '/api/game/$gameId/logo': typeof ApiGameGameIdLogoRoute
  '/api/organization/$organizationId/logo': typeof ApiOrganizationOrganizationIdLogoRoute
  '/api/user/$userId/avatar': typeof ApiUserUserIdAvatarRoute
  '/_layout/_authed/games/': typeof LayoutAuthedGamesIndexRoute
  '/_layout/_authed/organizations/': typeof LayoutAuthedOrganizationsIndexRoute
  '/_layout/_authed/players/': typeof LayoutAuthedPlayersIndexRoute
  '/_layout/_authed/games/$gameId/': typeof LayoutAuthedGamesGameIdIndexRoute
  '/_layout/_authed/games/$gameId/players/$playerId': typeof LayoutAuthedGamesGameIdPlayersPlayerIdRoute
  '/_layout/_authed/games/$gameId/players/': typeof LayoutAuthedGamesGameIdPlayersIndexRoute
  '/api/v1/game/$gameId/player/$playerId/reset-password': typeof ApiV1GameGameIdPlayerPlayerIdResetPasswordRoute
  '/api/v1/game/$gameId/player/$playerId/send-verification-email': typeof ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRoute
  '/api/v1/game/$gameId/player/session/revoke': typeof ApiV1GameGameIdPlayerSessionRevokeRoute
  '/api/v1/game/$gameId/player/sign-in/anonymously': typeof ApiV1GameGameIdPlayerSignInAnonymouslyRoute
  '/api/v1/game/$gameId/player/sign-in/email': typeof ApiV1GameGameIdPlayerSignInEmailRoute
  '/api/v1/game/$gameId/player/sign-up/email': typeof ApiV1GameGameIdPlayerSignUpEmailRoute
  '/api/v1/game/$gameId/player/$playerId/': typeof ApiV1GameGameIdPlayerPlayerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/api/health'
    | '/account'
    | '/api/auth/$'
    | '/api/user/avatar'
    | '/'
    | '/invitation/$invitationId/accept'
    | '/organizations/$organizationId'
    | '/api/game/$gameId/logo'
    | '/api/organization/$organizationId/logo'
    | '/api/user/$userId/avatar'
    | '/games'
    | '/organizations'
    | '/players'
    | '/games/$gameId'
    | '/games/$gameId/players/$playerId'
    | '/games/$gameId/players'
    | '/api/v1/game/$gameId/player/$playerId/reset-password'
    | '/api/v1/game/$gameId/player/$playerId/send-verification-email'
    | '/api/v1/game/$gameId/player/session/revoke'
    | '/api/v1/game/$gameId/player/sign-in/anonymously'
    | '/api/v1/game/$gameId/player/sign-in/email'
    | '/api/v1/game/$gameId/player/sign-up/email'
    | '/api/v1/game/$gameId/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/api/health'
    | '/account'
    | '/api/auth/$'
    | '/api/user/avatar'
    | '/'
    | '/invitation/$invitationId/accept'
    | '/organizations/$organizationId'
    | '/api/game/$gameId/logo'
    | '/api/organization/$organizationId/logo'
    | '/api/user/$userId/avatar'
    | '/games'
    | '/organizations'
    | '/players'
    | '/games/$gameId'
    | '/games/$gameId/players/$playerId'
    | '/games/$gameId/players'
    | '/api/v1/game/$gameId/player/$playerId/reset-password'
    | '/api/v1/game/$gameId/player/$playerId/send-verification-email'
    | '/api/v1/game/$gameId/player/session/revoke'
    | '/api/v1/game/$gameId/player/sign-in/anonymously'
    | '/api/v1/game/$gameId/player/sign-in/email'
    | '/api/v1/game/$gameId/player/sign-up/email'
    | '/api/v1/game/$gameId/player/$playerId'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/sign-up'
    | '/_layout/_authed'
    | '/api/health'
    | '/_layout/_authed/account'
    | '/api/auth/$'
    | '/api/user/avatar'
    | '/_layout/_authed/'
    | '/_auth/invitation/$invitationId/accept'
    | '/_layout/_authed/organizations/$organizationId'
    | '/api/game/$gameId/logo'
    | '/api/organization/$organizationId/logo'
    | '/api/user/$userId/avatar'
    | '/_layout/_authed/games/'
    | '/_layout/_authed/organizations/'
    | '/_layout/_authed/players/'
    | '/_layout/_authed/games/$gameId/'
    | '/_layout/_authed/games/$gameId/players/$playerId'
    | '/_layout/_authed/games/$gameId/players/'
    | '/api/v1/game/$gameId/player/$playerId/reset-password'
    | '/api/v1/game/$gameId/player/$playerId/send-verification-email'
    | '/api/v1/game/$gameId/player/session/revoke'
    | '/api/v1/game/$gameId/player/sign-in/anonymously'
    | '/api/v1/game/$gameId/player/sign-in/email'
    | '/api/v1/game/$gameId/player/sign-up/email'
    | '/api/v1/game/$gameId/player/$playerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserAvatarRoute: typeof ApiUserAvatarRoute
  ApiGameGameIdLogoRoute: typeof ApiGameGameIdLogoRoute
  ApiOrganizationOrganizationIdLogoRoute: typeof ApiOrganizationOrganizationIdLogoRoute
  ApiUserUserIdAvatarRoute: typeof ApiUserUserIdAvatarRoute
  ApiV1GameGameIdPlayerPlayerIdResetPasswordRoute: typeof ApiV1GameGameIdPlayerPlayerIdResetPasswordRoute
  ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRoute: typeof ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRoute
  ApiV1GameGameIdPlayerSessionRevokeRoute: typeof ApiV1GameGameIdPlayerSessionRevokeRoute
  ApiV1GameGameIdPlayerSignInAnonymouslyRoute: typeof ApiV1GameGameIdPlayerSignInAnonymouslyRoute
  ApiV1GameGameIdPlayerSignInEmailRoute: typeof ApiV1GameGameIdPlayerSignInEmailRoute
  ApiV1GameGameIdPlayerSignUpEmailRoute: typeof ApiV1GameGameIdPlayerSignUpEmailRoute
  ApiV1GameGameIdPlayerPlayerIdIndexRoute: typeof ApiV1GameGameIdPlayerPlayerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed': {
      id: '/_layout/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/_authed/': {
      id: '/_layout/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthedIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/api/user/avatar': {
      id: '/api/user/avatar'
      path: '/api/user/avatar'
      fullPath: '/api/user/avatar'
      preLoaderRoute: typeof ApiUserAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/account': {
      id: '/_layout/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAuthedAccountRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/players/': {
      id: '/_layout/_authed/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof LayoutAuthedPlayersIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/organizations/': {
      id: '/_layout/_authed/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof LayoutAuthedOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/games/': {
      id: '/_layout/_authed/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof LayoutAuthedGamesIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/api/user/$userId/avatar': {
      id: '/api/user/$userId/avatar'
      path: '/api/user/$userId/avatar'
      fullPath: '/api/user/$userId/avatar'
      preLoaderRoute: typeof ApiUserUserIdAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organization/$organizationId/logo': {
      id: '/api/organization/$organizationId/logo'
      path: '/api/organization/$organizationId/logo'
      fullPath: '/api/organization/$organizationId/logo'
      preLoaderRoute: typeof ApiOrganizationOrganizationIdLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/$gameId/logo': {
      id: '/api/game/$gameId/logo'
      path: '/api/game/$gameId/logo'
      fullPath: '/api/game/$gameId/logo'
      preLoaderRoute: typeof ApiGameGameIdLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/organizations/$organizationId': {
      id: '/_layout/_authed/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof LayoutAuthedOrganizationsOrganizationIdRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_auth/invitation/$invitationId/accept': {
      id: '/_auth/invitation/$invitationId/accept'
      path: '/invitation/$invitationId/accept'
      fullPath: '/invitation/$invitationId/accept'
      preLoaderRoute: typeof AuthInvitationInvitationIdAcceptRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/_authed/games/$gameId/': {
      id: '/_layout/_authed/games/$gameId/'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof LayoutAuthedGamesGameIdIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/games/$gameId/players/': {
      id: '/_layout/_authed/games/$gameId/players/'
      path: '/games/$gameId/players'
      fullPath: '/games/$gameId/players'
      preLoaderRoute: typeof LayoutAuthedGamesGameIdPlayersIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/games/$gameId/players/$playerId': {
      id: '/_layout/_authed/games/$gameId/players/$playerId'
      path: '/games/$gameId/players/$playerId'
      fullPath: '/games/$gameId/players/$playerId'
      preLoaderRoute: typeof LayoutAuthedGamesGameIdPlayersPlayerIdRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/api/v1/game/$gameId/player/$playerId/': {
      id: '/api/v1/game/$gameId/player/$playerId/'
      path: '/api/v1/game/$gameId/player/$playerId'
      fullPath: '/api/v1/game/$gameId/player/$playerId'
      preLoaderRoute: typeof ApiV1GameGameIdPlayerPlayerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game/$gameId/player/sign-up/email': {
      id: '/api/v1/game/$gameId/player/sign-up/email'
      path: '/api/v1/game/$gameId/player/sign-up/email'
      fullPath: '/api/v1/game/$gameId/player/sign-up/email'
      preLoaderRoute: typeof ApiV1GameGameIdPlayerSignUpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game/$gameId/player/sign-in/email': {
      id: '/api/v1/game/$gameId/player/sign-in/email'
      path: '/api/v1/game/$gameId/player/sign-in/email'
      fullPath: '/api/v1/game/$gameId/player/sign-in/email'
      preLoaderRoute: typeof ApiV1GameGameIdPlayerSignInEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game/$gameId/player/sign-in/anonymously': {
      id: '/api/v1/game/$gameId/player/sign-in/anonymously'
      path: '/api/v1/game/$gameId/player/sign-in/anonymously'
      fullPath: '/api/v1/game/$gameId/player/sign-in/anonymously'
      preLoaderRoute: typeof ApiV1GameGameIdPlayerSignInAnonymouslyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game/$gameId/player/session/revoke': {
      id: '/api/v1/game/$gameId/player/session/revoke'
      path: '/api/v1/game/$gameId/player/session/revoke'
      fullPath: '/api/v1/game/$gameId/player/session/revoke'
      preLoaderRoute: typeof ApiV1GameGameIdPlayerSessionRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game/$gameId/player/$playerId/send-verification-email': {
      id: '/api/v1/game/$gameId/player/$playerId/send-verification-email'
      path: '/api/v1/game/$gameId/player/$playerId/send-verification-email'
      fullPath: '/api/v1/game/$gameId/player/$playerId/send-verification-email'
      preLoaderRoute: typeof ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/game/$gameId/player/$playerId/reset-password': {
      id: '/api/v1/game/$gameId/player/$playerId/reset-password'
      path: '/api/v1/game/$gameId/player/$playerId/reset-password'
      fullPath: '/api/v1/game/$gameId/player/$playerId/reset-password'
      preLoaderRoute: typeof ApiV1GameGameIdPlayerPlayerIdResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthInvitationInvitationIdAcceptRoute: typeof AuthInvitationInvitationIdAcceptRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthInvitationInvitationIdAcceptRoute: AuthInvitationInvitationIdAcceptRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutAuthedRouteChildren {
  LayoutAuthedAccountRoute: typeof LayoutAuthedAccountRoute
  LayoutAuthedIndexRoute: typeof LayoutAuthedIndexRoute
  LayoutAuthedOrganizationsOrganizationIdRoute: typeof LayoutAuthedOrganizationsOrganizationIdRoute
  LayoutAuthedGamesIndexRoute: typeof LayoutAuthedGamesIndexRoute
  LayoutAuthedOrganizationsIndexRoute: typeof LayoutAuthedOrganizationsIndexRoute
  LayoutAuthedPlayersIndexRoute: typeof LayoutAuthedPlayersIndexRoute
  LayoutAuthedGamesGameIdIndexRoute: typeof LayoutAuthedGamesGameIdIndexRoute
  LayoutAuthedGamesGameIdPlayersPlayerIdRoute: typeof LayoutAuthedGamesGameIdPlayersPlayerIdRoute
  LayoutAuthedGamesGameIdPlayersIndexRoute: typeof LayoutAuthedGamesGameIdPlayersIndexRoute
}

const LayoutAuthedRouteChildren: LayoutAuthedRouteChildren = {
  LayoutAuthedAccountRoute: LayoutAuthedAccountRoute,
  LayoutAuthedIndexRoute: LayoutAuthedIndexRoute,
  LayoutAuthedOrganizationsOrganizationIdRoute:
    LayoutAuthedOrganizationsOrganizationIdRoute,
  LayoutAuthedGamesIndexRoute: LayoutAuthedGamesIndexRoute,
  LayoutAuthedOrganizationsIndexRoute: LayoutAuthedOrganizationsIndexRoute,
  LayoutAuthedPlayersIndexRoute: LayoutAuthedPlayersIndexRoute,
  LayoutAuthedGamesGameIdIndexRoute: LayoutAuthedGamesGameIdIndexRoute,
  LayoutAuthedGamesGameIdPlayersPlayerIdRoute:
    LayoutAuthedGamesGameIdPlayersPlayerIdRoute,
  LayoutAuthedGamesGameIdPlayersIndexRoute:
    LayoutAuthedGamesGameIdPlayersIndexRoute,
}

const LayoutAuthedRouteWithChildren = LayoutAuthedRoute._addFileChildren(
  LayoutAuthedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthedRoute: typeof LayoutAuthedRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthedRoute: LayoutAuthedRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserAvatarRoute: ApiUserAvatarRoute,
  ApiGameGameIdLogoRoute: ApiGameGameIdLogoRoute,
  ApiOrganizationOrganizationIdLogoRoute:
    ApiOrganizationOrganizationIdLogoRoute,
  ApiUserUserIdAvatarRoute: ApiUserUserIdAvatarRoute,
  ApiV1GameGameIdPlayerPlayerIdResetPasswordRoute:
    ApiV1GameGameIdPlayerPlayerIdResetPasswordRoute,
  ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRoute:
    ApiV1GameGameIdPlayerPlayerIdSendVerificationEmailRoute,
  ApiV1GameGameIdPlayerSessionRevokeRoute:
    ApiV1GameGameIdPlayerSessionRevokeRoute,
  ApiV1GameGameIdPlayerSignInAnonymouslyRoute:
    ApiV1GameGameIdPlayerSignInAnonymouslyRoute,
  ApiV1GameGameIdPlayerSignInEmailRoute: ApiV1GameGameIdPlayerSignInEmailRoute,
  ApiV1GameGameIdPlayerSignUpEmailRoute: ApiV1GameGameIdPlayerSignUpEmailRoute,
  ApiV1GameGameIdPlayerPlayerIdIndexRoute:
    ApiV1GameGameIdPlayerPlayerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
