/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LayoutAuthedRouteImport } from './routes/_layout/_authed'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as LayoutAuthedIndexRouteImport } from './routes/_layout/_authed/index'
import { Route as ApiUserAvatarRouteImport } from './routes/api/user/avatar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutAuthedAccountRouteImport } from './routes/_layout/_authed/account'
import { Route as LayoutAuthedPlayersIndexRouteImport } from './routes/_layout/_authed/players/index'
import { Route as LayoutAuthedOrganizationsIndexRouteImport } from './routes/_layout/_authed/organizations/index'
import { Route as LayoutAuthedGamesIndexRouteImport } from './routes/_layout/_authed/games/index'
import { Route as ApiPlayerAuthGameIdSplatRouteImport } from './routes/api/player-auth/$gameId/$'
import { Route as ApiOrganizationsOrganizationIdLogoRouteImport } from './routes/api/organizations/$organizationId/logo'
import { Route as ApiGamesGameIdLogoRouteImport } from './routes/api/games/$gameId/logo'
import { Route as LayoutAuthedOrganizationsOrganizationIdRouteImport } from './routes/_layout/_authed/organizations/$organizationId'
import { Route as AuthInvitationInvitationIdAcceptRouteImport } from './routes/_auth/invitation/$invitationId/accept'
import { Route as LayoutAuthedGamesGameIdIndexRouteImport } from './routes/_layout/_authed/games/$gameId/index'
import { Route as AuthPlayerAuthGamesGameIdResetPasswordRouteImport } from './routes/_auth/_player-auth/games/$gameId/reset-password'
import { Route as AuthPlayerAuthGamesGameIdEmailVerifiedRouteImport } from './routes/_auth/_player-auth/games/$gameId/email-verified'
import { Route as AuthPlayerAuthGamesGameIdChangeEmailRequestedRouteImport } from './routes/_auth/_player-auth/games/$gameId/change-email-requested'
import { Route as ApiV1GamesGameIdPlayerIndexRouteImport } from './routes/api/v1/games/$gameId/player/index'
import { Route as LayoutAuthedGamesGameIdPlayersIndexRouteImport } from './routes/_layout/_authed/games/$gameId/players/index'
import { Route as ApiV1GamesGameIdPlayerSignOutRouteImport } from './routes/api/v1/games/$gameId/player/sign-out'
import { Route as ApiV1GamesGameIdPlayerChangeEmailRouteImport } from './routes/api/v1/games/$gameId/player/change-email'
import { Route as ApiV1GamesGameIdAuthResetPasswordRouteImport } from './routes/api/v1/games/$gameId/auth/reset-password'
import { Route as ApiV1GamesGameIdAuthResendVerificationRouteImport } from './routes/api/v1/games/$gameId/auth/resend-verification'
import { Route as ApiOrganizationsOrganizationIdUsersUserIdAvatarRouteImport } from './routes/api/organizations/$organizationId/users/$userId/avatar'
import { Route as LayoutAuthedGamesGameIdPlayersPlayerIdRouteImport } from './routes/_layout/_authed/games/$gameId/players/$playerId'
import { Route as ApiV1GamesGameIdAuthSignUpEmailRouteImport } from './routes/api/v1/games/$gameId/auth/sign-up/email'
import { Route as ApiV1GamesGameIdAuthSignInEmailRouteImport } from './routes/api/v1/games/$gameId/auth/sign-in/email'
import { Route as ApiV1GamesGameIdAuthSignInAnonymouslyRouteImport } from './routes/api/v1/games/$gameId/auth/sign-in/anonymously'
import { Route as ApiV1AdminGamesGameIdPlayersPlayerIdIndexRouteImport } from './routes/api/v1/admin/games/$gameId/players/$playerId/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedRoute = LayoutAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutAuthedIndexRoute = LayoutAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const ApiUserAvatarRoute = ApiUserAvatarRouteImport.update({
  id: '/api/user/avatar',
  path: '/api/user/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedAccountRoute = LayoutAuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const LayoutAuthedPlayersIndexRoute =
  LayoutAuthedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedOrganizationsIndexRoute =
  LayoutAuthedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedGamesIndexRoute = LayoutAuthedGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const ApiPlayerAuthGameIdSplatRoute =
  ApiPlayerAuthGameIdSplatRouteImport.update({
    id: '/api/player-auth/$gameId/$',
    path: '/api/player-auth/$gameId/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsOrganizationIdLogoRoute =
  ApiOrganizationsOrganizationIdLogoRouteImport.update({
    id: '/api/organizations/$organizationId/logo',
    path: '/api/organizations/$organizationId/logo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamesGameIdLogoRoute = ApiGamesGameIdLogoRouteImport.update({
  id: '/api/games/$gameId/logo',
  path: '/api/games/$gameId/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedOrganizationsOrganizationIdRoute =
  LayoutAuthedOrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const AuthInvitationInvitationIdAcceptRoute =
  AuthInvitationInvitationIdAcceptRouteImport.update({
    id: '/invitation/$invitationId/accept',
    path: '/invitation/$invitationId/accept',
    getParentRoute: () => AuthRoute,
  } as any)
const LayoutAuthedGamesGameIdIndexRoute =
  LayoutAuthedGamesGameIdIndexRouteImport.update({
    id: '/games/$gameId/',
    path: '/games/$gameId/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const AuthPlayerAuthGamesGameIdResetPasswordRoute =
  AuthPlayerAuthGamesGameIdResetPasswordRouteImport.update({
    id: '/_player-auth/games/$gameId/reset-password',
    path: '/games/$gameId/reset-password',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPlayerAuthGamesGameIdEmailVerifiedRoute =
  AuthPlayerAuthGamesGameIdEmailVerifiedRouteImport.update({
    id: '/_player-auth/games/$gameId/email-verified',
    path: '/games/$gameId/email-verified',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthPlayerAuthGamesGameIdChangeEmailRequestedRoute =
  AuthPlayerAuthGamesGameIdChangeEmailRequestedRouteImport.update({
    id: '/_player-auth/games/$gameId/change-email-requested',
    path: '/games/$gameId/change-email-requested',
    getParentRoute: () => AuthRoute,
  } as any)
const ApiV1GamesGameIdPlayerIndexRoute =
  ApiV1GamesGameIdPlayerIndexRouteImport.update({
    id: '/api/v1/games/$gameId/player/',
    path: '/api/v1/games/$gameId/player/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthedGamesGameIdPlayersIndexRoute =
  LayoutAuthedGamesGameIdPlayersIndexRouteImport.update({
    id: '/games/$gameId/players/',
    path: '/games/$gameId/players/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const ApiV1GamesGameIdPlayerSignOutRoute =
  ApiV1GamesGameIdPlayerSignOutRouteImport.update({
    id: '/api/v1/games/$gameId/player/sign-out',
    path: '/api/v1/games/$gameId/player/sign-out',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GamesGameIdPlayerChangeEmailRoute =
  ApiV1GamesGameIdPlayerChangeEmailRouteImport.update({
    id: '/api/v1/games/$gameId/player/change-email',
    path: '/api/v1/games/$gameId/player/change-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GamesGameIdAuthResetPasswordRoute =
  ApiV1GamesGameIdAuthResetPasswordRouteImport.update({
    id: '/api/v1/games/$gameId/auth/reset-password',
    path: '/api/v1/games/$gameId/auth/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GamesGameIdAuthResendVerificationRoute =
  ApiV1GamesGameIdAuthResendVerificationRouteImport.update({
    id: '/api/v1/games/$gameId/auth/resend-verification',
    path: '/api/v1/games/$gameId/auth/resend-verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrganizationsOrganizationIdUsersUserIdAvatarRoute =
  ApiOrganizationsOrganizationIdUsersUserIdAvatarRouteImport.update({
    id: '/api/organizations/$organizationId/users/$userId/avatar',
    path: '/api/organizations/$organizationId/users/$userId/avatar',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutAuthedGamesGameIdPlayersPlayerIdRoute =
  LayoutAuthedGamesGameIdPlayersPlayerIdRouteImport.update({
    id: '/games/$gameId/players/$playerId',
    path: '/games/$gameId/players/$playerId',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const ApiV1GamesGameIdAuthSignUpEmailRoute =
  ApiV1GamesGameIdAuthSignUpEmailRouteImport.update({
    id: '/api/v1/games/$gameId/auth/sign-up/email',
    path: '/api/v1/games/$gameId/auth/sign-up/email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GamesGameIdAuthSignInEmailRoute =
  ApiV1GamesGameIdAuthSignInEmailRouteImport.update({
    id: '/api/v1/games/$gameId/auth/sign-in/email',
    path: '/api/v1/games/$gameId/auth/sign-in/email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1GamesGameIdAuthSignInAnonymouslyRoute =
  ApiV1GamesGameIdAuthSignInAnonymouslyRouteImport.update({
    id: '/api/v1/games/$gameId/auth/sign-in/anonymously',
    path: '/api/v1/games/$gameId/auth/sign-in/anonymously',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AdminGamesGameIdPlayersPlayerIdIndexRoute =
  ApiV1AdminGamesGameIdPlayersPlayerIdIndexRouteImport.update({
    id: '/api/v1/admin/games/$gameId/players/$playerId/',
    path: '/api/v1/admin/games/$gameId/players/$playerId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/account': typeof LayoutAuthedAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/avatar': typeof ApiUserAvatarRoute
  '/': typeof LayoutAuthedIndexRoute
  '/invitation/$invitationId/accept': typeof AuthInvitationInvitationIdAcceptRoute
  '/organizations/$organizationId': typeof LayoutAuthedOrganizationsOrganizationIdRoute
  '/api/games/$gameId/logo': typeof ApiGamesGameIdLogoRoute
  '/api/organizations/$organizationId/logo': typeof ApiOrganizationsOrganizationIdLogoRoute
  '/api/player-auth/$gameId/$': typeof ApiPlayerAuthGameIdSplatRoute
  '/games': typeof LayoutAuthedGamesIndexRoute
  '/organizations': typeof LayoutAuthedOrganizationsIndexRoute
  '/players': typeof LayoutAuthedPlayersIndexRoute
  '/games/$gameId/change-email-requested': typeof AuthPlayerAuthGamesGameIdChangeEmailRequestedRoute
  '/games/$gameId/email-verified': typeof AuthPlayerAuthGamesGameIdEmailVerifiedRoute
  '/games/$gameId/reset-password': typeof AuthPlayerAuthGamesGameIdResetPasswordRoute
  '/games/$gameId': typeof LayoutAuthedGamesGameIdIndexRoute
  '/games/$gameId/players/$playerId': typeof LayoutAuthedGamesGameIdPlayersPlayerIdRoute
  '/api/organizations/$organizationId/users/$userId/avatar': typeof ApiOrganizationsOrganizationIdUsersUserIdAvatarRoute
  '/api/v1/games/$gameId/auth/resend-verification': typeof ApiV1GamesGameIdAuthResendVerificationRoute
  '/api/v1/games/$gameId/auth/reset-password': typeof ApiV1GamesGameIdAuthResetPasswordRoute
  '/api/v1/games/$gameId/player/change-email': typeof ApiV1GamesGameIdPlayerChangeEmailRoute
  '/api/v1/games/$gameId/player/sign-out': typeof ApiV1GamesGameIdPlayerSignOutRoute
  '/games/$gameId/players': typeof LayoutAuthedGamesGameIdPlayersIndexRoute
  '/api/v1/games/$gameId/player': typeof ApiV1GamesGameIdPlayerIndexRoute
  '/api/v1/games/$gameId/auth/sign-in/anonymously': typeof ApiV1GamesGameIdAuthSignInAnonymouslyRoute
  '/api/v1/games/$gameId/auth/sign-in/email': typeof ApiV1GamesGameIdAuthSignInEmailRoute
  '/api/v1/games/$gameId/auth/sign-up/email': typeof ApiV1GamesGameIdAuthSignUpEmailRoute
  '/api/v1/admin/games/$gameId/players/$playerId': typeof ApiV1AdminGamesGameIdPlayersPlayerIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/health': typeof ApiHealthRoute
  '/account': typeof LayoutAuthedAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/avatar': typeof ApiUserAvatarRoute
  '/': typeof LayoutAuthedIndexRoute
  '/invitation/$invitationId/accept': typeof AuthInvitationInvitationIdAcceptRoute
  '/organizations/$organizationId': typeof LayoutAuthedOrganizationsOrganizationIdRoute
  '/api/games/$gameId/logo': typeof ApiGamesGameIdLogoRoute
  '/api/organizations/$organizationId/logo': typeof ApiOrganizationsOrganizationIdLogoRoute
  '/api/player-auth/$gameId/$': typeof ApiPlayerAuthGameIdSplatRoute
  '/games': typeof LayoutAuthedGamesIndexRoute
  '/organizations': typeof LayoutAuthedOrganizationsIndexRoute
  '/players': typeof LayoutAuthedPlayersIndexRoute
  '/games/$gameId/change-email-requested': typeof AuthPlayerAuthGamesGameIdChangeEmailRequestedRoute
  '/games/$gameId/email-verified': typeof AuthPlayerAuthGamesGameIdEmailVerifiedRoute
  '/games/$gameId/reset-password': typeof AuthPlayerAuthGamesGameIdResetPasswordRoute
  '/games/$gameId': typeof LayoutAuthedGamesGameIdIndexRoute
  '/games/$gameId/players/$playerId': typeof LayoutAuthedGamesGameIdPlayersPlayerIdRoute
  '/api/organizations/$organizationId/users/$userId/avatar': typeof ApiOrganizationsOrganizationIdUsersUserIdAvatarRoute
  '/api/v1/games/$gameId/auth/resend-verification': typeof ApiV1GamesGameIdAuthResendVerificationRoute
  '/api/v1/games/$gameId/auth/reset-password': typeof ApiV1GamesGameIdAuthResetPasswordRoute
  '/api/v1/games/$gameId/player/change-email': typeof ApiV1GamesGameIdPlayerChangeEmailRoute
  '/api/v1/games/$gameId/player/sign-out': typeof ApiV1GamesGameIdPlayerSignOutRoute
  '/games/$gameId/players': typeof LayoutAuthedGamesGameIdPlayersIndexRoute
  '/api/v1/games/$gameId/player': typeof ApiV1GamesGameIdPlayerIndexRoute
  '/api/v1/games/$gameId/auth/sign-in/anonymously': typeof ApiV1GamesGameIdAuthSignInAnonymouslyRoute
  '/api/v1/games/$gameId/auth/sign-in/email': typeof ApiV1GamesGameIdAuthSignInEmailRoute
  '/api/v1/games/$gameId/auth/sign-up/email': typeof ApiV1GamesGameIdAuthSignUpEmailRoute
  '/api/v1/admin/games/$gameId/players/$playerId': typeof ApiV1AdminGamesGameIdPlayersPlayerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_layout/_authed': typeof LayoutAuthedRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/_layout/_authed/account': typeof LayoutAuthedAccountRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/avatar': typeof ApiUserAvatarRoute
  '/_layout/_authed/': typeof LayoutAuthedIndexRoute
  '/_auth/invitation/$invitationId/accept': typeof AuthInvitationInvitationIdAcceptRoute
  '/_layout/_authed/organizations/$organizationId': typeof LayoutAuthedOrganizationsOrganizationIdRoute
  '/api/games/$gameId/logo': typeof ApiGamesGameIdLogoRoute
  '/api/organizations/$organizationId/logo': typeof ApiOrganizationsOrganizationIdLogoRoute
  '/api/player-auth/$gameId/$': typeof ApiPlayerAuthGameIdSplatRoute
  '/_layout/_authed/games/': typeof LayoutAuthedGamesIndexRoute
  '/_layout/_authed/organizations/': typeof LayoutAuthedOrganizationsIndexRoute
  '/_layout/_authed/players/': typeof LayoutAuthedPlayersIndexRoute
  '/_auth/_player-auth/games/$gameId/change-email-requested': typeof AuthPlayerAuthGamesGameIdChangeEmailRequestedRoute
  '/_auth/_player-auth/games/$gameId/email-verified': typeof AuthPlayerAuthGamesGameIdEmailVerifiedRoute
  '/_auth/_player-auth/games/$gameId/reset-password': typeof AuthPlayerAuthGamesGameIdResetPasswordRoute
  '/_layout/_authed/games/$gameId/': typeof LayoutAuthedGamesGameIdIndexRoute
  '/_layout/_authed/games/$gameId/players/$playerId': typeof LayoutAuthedGamesGameIdPlayersPlayerIdRoute
  '/api/organizations/$organizationId/users/$userId/avatar': typeof ApiOrganizationsOrganizationIdUsersUserIdAvatarRoute
  '/api/v1/games/$gameId/auth/resend-verification': typeof ApiV1GamesGameIdAuthResendVerificationRoute
  '/api/v1/games/$gameId/auth/reset-password': typeof ApiV1GamesGameIdAuthResetPasswordRoute
  '/api/v1/games/$gameId/player/change-email': typeof ApiV1GamesGameIdPlayerChangeEmailRoute
  '/api/v1/games/$gameId/player/sign-out': typeof ApiV1GamesGameIdPlayerSignOutRoute
  '/_layout/_authed/games/$gameId/players/': typeof LayoutAuthedGamesGameIdPlayersIndexRoute
  '/api/v1/games/$gameId/player/': typeof ApiV1GamesGameIdPlayerIndexRoute
  '/api/v1/games/$gameId/auth/sign-in/anonymously': typeof ApiV1GamesGameIdAuthSignInAnonymouslyRoute
  '/api/v1/games/$gameId/auth/sign-in/email': typeof ApiV1GamesGameIdAuthSignInEmailRoute
  '/api/v1/games/$gameId/auth/sign-up/email': typeof ApiV1GamesGameIdAuthSignUpEmailRoute
  '/api/v1/admin/games/$gameId/players/$playerId/': typeof ApiV1AdminGamesGameIdPlayersPlayerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/api/health'
    | '/account'
    | '/api/auth/$'
    | '/api/user/avatar'
    | '/'
    | '/invitation/$invitationId/accept'
    | '/organizations/$organizationId'
    | '/api/games/$gameId/logo'
    | '/api/organizations/$organizationId/logo'
    | '/api/player-auth/$gameId/$'
    | '/games'
    | '/organizations'
    | '/players'
    | '/games/$gameId/change-email-requested'
    | '/games/$gameId/email-verified'
    | '/games/$gameId/reset-password'
    | '/games/$gameId'
    | '/games/$gameId/players/$playerId'
    | '/api/organizations/$organizationId/users/$userId/avatar'
    | '/api/v1/games/$gameId/auth/resend-verification'
    | '/api/v1/games/$gameId/auth/reset-password'
    | '/api/v1/games/$gameId/player/change-email'
    | '/api/v1/games/$gameId/player/sign-out'
    | '/games/$gameId/players'
    | '/api/v1/games/$gameId/player'
    | '/api/v1/games/$gameId/auth/sign-in/anonymously'
    | '/api/v1/games/$gameId/auth/sign-in/email'
    | '/api/v1/games/$gameId/auth/sign-up/email'
    | '/api/v1/admin/games/$gameId/players/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/api/health'
    | '/account'
    | '/api/auth/$'
    | '/api/user/avatar'
    | '/'
    | '/invitation/$invitationId/accept'
    | '/organizations/$organizationId'
    | '/api/games/$gameId/logo'
    | '/api/organizations/$organizationId/logo'
    | '/api/player-auth/$gameId/$'
    | '/games'
    | '/organizations'
    | '/players'
    | '/games/$gameId/change-email-requested'
    | '/games/$gameId/email-verified'
    | '/games/$gameId/reset-password'
    | '/games/$gameId'
    | '/games/$gameId/players/$playerId'
    | '/api/organizations/$organizationId/users/$userId/avatar'
    | '/api/v1/games/$gameId/auth/resend-verification'
    | '/api/v1/games/$gameId/auth/reset-password'
    | '/api/v1/games/$gameId/player/change-email'
    | '/api/v1/games/$gameId/player/sign-out'
    | '/games/$gameId/players'
    | '/api/v1/games/$gameId/player'
    | '/api/v1/games/$gameId/auth/sign-in/anonymously'
    | '/api/v1/games/$gameId/auth/sign-in/email'
    | '/api/v1/games/$gameId/auth/sign-up/email'
    | '/api/v1/admin/games/$gameId/players/$playerId'
  id:
    | '__root__'
    | '/_auth'
    | '/_layout'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/sign-up'
    | '/_layout/_authed'
    | '/api/health'
    | '/_layout/_authed/account'
    | '/api/auth/$'
    | '/api/user/avatar'
    | '/_layout/_authed/'
    | '/_auth/invitation/$invitationId/accept'
    | '/_layout/_authed/organizations/$organizationId'
    | '/api/games/$gameId/logo'
    | '/api/organizations/$organizationId/logo'
    | '/api/player-auth/$gameId/$'
    | '/_layout/_authed/games/'
    | '/_layout/_authed/organizations/'
    | '/_layout/_authed/players/'
    | '/_auth/_player-auth/games/$gameId/change-email-requested'
    | '/_auth/_player-auth/games/$gameId/email-verified'
    | '/_auth/_player-auth/games/$gameId/reset-password'
    | '/_layout/_authed/games/$gameId/'
    | '/_layout/_authed/games/$gameId/players/$playerId'
    | '/api/organizations/$organizationId/users/$userId/avatar'
    | '/api/v1/games/$gameId/auth/resend-verification'
    | '/api/v1/games/$gameId/auth/reset-password'
    | '/api/v1/games/$gameId/player/change-email'
    | '/api/v1/games/$gameId/player/sign-out'
    | '/_layout/_authed/games/$gameId/players/'
    | '/api/v1/games/$gameId/player/'
    | '/api/v1/games/$gameId/auth/sign-in/anonymously'
    | '/api/v1/games/$gameId/auth/sign-in/email'
    | '/api/v1/games/$gameId/auth/sign-up/email'
    | '/api/v1/admin/games/$gameId/players/$playerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserAvatarRoute: typeof ApiUserAvatarRoute
  ApiGamesGameIdLogoRoute: typeof ApiGamesGameIdLogoRoute
  ApiOrganizationsOrganizationIdLogoRoute: typeof ApiOrganizationsOrganizationIdLogoRoute
  ApiPlayerAuthGameIdSplatRoute: typeof ApiPlayerAuthGameIdSplatRoute
  ApiOrganizationsOrganizationIdUsersUserIdAvatarRoute: typeof ApiOrganizationsOrganizationIdUsersUserIdAvatarRoute
  ApiV1GamesGameIdAuthResendVerificationRoute: typeof ApiV1GamesGameIdAuthResendVerificationRoute
  ApiV1GamesGameIdAuthResetPasswordRoute: typeof ApiV1GamesGameIdAuthResetPasswordRoute
  ApiV1GamesGameIdPlayerChangeEmailRoute: typeof ApiV1GamesGameIdPlayerChangeEmailRoute
  ApiV1GamesGameIdPlayerSignOutRoute: typeof ApiV1GamesGameIdPlayerSignOutRoute
  ApiV1GamesGameIdPlayerIndexRoute: typeof ApiV1GamesGameIdPlayerIndexRoute
  ApiV1GamesGameIdAuthSignInAnonymouslyRoute: typeof ApiV1GamesGameIdAuthSignInAnonymouslyRoute
  ApiV1GamesGameIdAuthSignInEmailRoute: typeof ApiV1GamesGameIdAuthSignInEmailRoute
  ApiV1GamesGameIdAuthSignUpEmailRoute: typeof ApiV1GamesGameIdAuthSignUpEmailRoute
  ApiV1AdminGamesGameIdPlayersPlayerIdIndexRoute: typeof ApiV1AdminGamesGameIdPlayersPlayerIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed': {
      id: '/_layout/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/_authed/': {
      id: '/_layout/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthedIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/api/user/avatar': {
      id: '/api/user/avatar'
      path: '/api/user/avatar'
      fullPath: '/api/user/avatar'
      preLoaderRoute: typeof ApiUserAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/account': {
      id: '/_layout/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAuthedAccountRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/players/': {
      id: '/_layout/_authed/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof LayoutAuthedPlayersIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/organizations/': {
      id: '/_layout/_authed/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof LayoutAuthedOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/games/': {
      id: '/_layout/_authed/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof LayoutAuthedGamesIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/api/player-auth/$gameId/$': {
      id: '/api/player-auth/$gameId/$'
      path: '/api/player-auth/$gameId/$'
      fullPath: '/api/player-auth/$gameId/$'
      preLoaderRoute: typeof ApiPlayerAuthGameIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/$organizationId/logo': {
      id: '/api/organizations/$organizationId/logo'
      path: '/api/organizations/$organizationId/logo'
      fullPath: '/api/organizations/$organizationId/logo'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games/$gameId/logo': {
      id: '/api/games/$gameId/logo'
      path: '/api/games/$gameId/logo'
      fullPath: '/api/games/$gameId/logo'
      preLoaderRoute: typeof ApiGamesGameIdLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/organizations/$organizationId': {
      id: '/_layout/_authed/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof LayoutAuthedOrganizationsOrganizationIdRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_auth/invitation/$invitationId/accept': {
      id: '/_auth/invitation/$invitationId/accept'
      path: '/invitation/$invitationId/accept'
      fullPath: '/invitation/$invitationId/accept'
      preLoaderRoute: typeof AuthInvitationInvitationIdAcceptRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/_authed/games/$gameId/': {
      id: '/_layout/_authed/games/$gameId/'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof LayoutAuthedGamesGameIdIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_auth/_player-auth/games/$gameId/reset-password': {
      id: '/_auth/_player-auth/games/$gameId/reset-password'
      path: '/games/$gameId/reset-password'
      fullPath: '/games/$gameId/reset-password'
      preLoaderRoute: typeof AuthPlayerAuthGamesGameIdResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_player-auth/games/$gameId/email-verified': {
      id: '/_auth/_player-auth/games/$gameId/email-verified'
      path: '/games/$gameId/email-verified'
      fullPath: '/games/$gameId/email-verified'
      preLoaderRoute: typeof AuthPlayerAuthGamesGameIdEmailVerifiedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_player-auth/games/$gameId/change-email-requested': {
      id: '/_auth/_player-auth/games/$gameId/change-email-requested'
      path: '/games/$gameId/change-email-requested'
      fullPath: '/games/$gameId/change-email-requested'
      preLoaderRoute: typeof AuthPlayerAuthGamesGameIdChangeEmailRequestedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/v1/games/$gameId/player/': {
      id: '/api/v1/games/$gameId/player/'
      path: '/api/v1/games/$gameId/player'
      fullPath: '/api/v1/games/$gameId/player'
      preLoaderRoute: typeof ApiV1GamesGameIdPlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/games/$gameId/players/': {
      id: '/_layout/_authed/games/$gameId/players/'
      path: '/games/$gameId/players'
      fullPath: '/games/$gameId/players'
      preLoaderRoute: typeof LayoutAuthedGamesGameIdPlayersIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/api/v1/games/$gameId/player/sign-out': {
      id: '/api/v1/games/$gameId/player/sign-out'
      path: '/api/v1/games/$gameId/player/sign-out'
      fullPath: '/api/v1/games/$gameId/player/sign-out'
      preLoaderRoute: typeof ApiV1GamesGameIdPlayerSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/games/$gameId/player/change-email': {
      id: '/api/v1/games/$gameId/player/change-email'
      path: '/api/v1/games/$gameId/player/change-email'
      fullPath: '/api/v1/games/$gameId/player/change-email'
      preLoaderRoute: typeof ApiV1GamesGameIdPlayerChangeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/games/$gameId/auth/reset-password': {
      id: '/api/v1/games/$gameId/auth/reset-password'
      path: '/api/v1/games/$gameId/auth/reset-password'
      fullPath: '/api/v1/games/$gameId/auth/reset-password'
      preLoaderRoute: typeof ApiV1GamesGameIdAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/games/$gameId/auth/resend-verification': {
      id: '/api/v1/games/$gameId/auth/resend-verification'
      path: '/api/v1/games/$gameId/auth/resend-verification'
      fullPath: '/api/v1/games/$gameId/auth/resend-verification'
      preLoaderRoute: typeof ApiV1GamesGameIdAuthResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/$organizationId/users/$userId/avatar': {
      id: '/api/organizations/$organizationId/users/$userId/avatar'
      path: '/api/organizations/$organizationId/users/$userId/avatar'
      fullPath: '/api/organizations/$organizationId/users/$userId/avatar'
      preLoaderRoute: typeof ApiOrganizationsOrganizationIdUsersUserIdAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/games/$gameId/players/$playerId': {
      id: '/_layout/_authed/games/$gameId/players/$playerId'
      path: '/games/$gameId/players/$playerId'
      fullPath: '/games/$gameId/players/$playerId'
      preLoaderRoute: typeof LayoutAuthedGamesGameIdPlayersPlayerIdRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/api/v1/games/$gameId/auth/sign-up/email': {
      id: '/api/v1/games/$gameId/auth/sign-up/email'
      path: '/api/v1/games/$gameId/auth/sign-up/email'
      fullPath: '/api/v1/games/$gameId/auth/sign-up/email'
      preLoaderRoute: typeof ApiV1GamesGameIdAuthSignUpEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/games/$gameId/auth/sign-in/email': {
      id: '/api/v1/games/$gameId/auth/sign-in/email'
      path: '/api/v1/games/$gameId/auth/sign-in/email'
      fullPath: '/api/v1/games/$gameId/auth/sign-in/email'
      preLoaderRoute: typeof ApiV1GamesGameIdAuthSignInEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/games/$gameId/auth/sign-in/anonymously': {
      id: '/api/v1/games/$gameId/auth/sign-in/anonymously'
      path: '/api/v1/games/$gameId/auth/sign-in/anonymously'
      fullPath: '/api/v1/games/$gameId/auth/sign-in/anonymously'
      preLoaderRoute: typeof ApiV1GamesGameIdAuthSignInAnonymouslyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/admin/games/$gameId/players/$playerId/': {
      id: '/api/v1/admin/games/$gameId/players/$playerId/'
      path: '/api/v1/admin/games/$gameId/players/$playerId'
      fullPath: '/api/v1/admin/games/$gameId/players/$playerId'
      preLoaderRoute: typeof ApiV1AdminGamesGameIdPlayersPlayerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthInvitationInvitationIdAcceptRoute: typeof AuthInvitationInvitationIdAcceptRoute
  AuthPlayerAuthGamesGameIdChangeEmailRequestedRoute: typeof AuthPlayerAuthGamesGameIdChangeEmailRequestedRoute
  AuthPlayerAuthGamesGameIdEmailVerifiedRoute: typeof AuthPlayerAuthGamesGameIdEmailVerifiedRoute
  AuthPlayerAuthGamesGameIdResetPasswordRoute: typeof AuthPlayerAuthGamesGameIdResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthInvitationInvitationIdAcceptRoute: AuthInvitationInvitationIdAcceptRoute,
  AuthPlayerAuthGamesGameIdChangeEmailRequestedRoute:
    AuthPlayerAuthGamesGameIdChangeEmailRequestedRoute,
  AuthPlayerAuthGamesGameIdEmailVerifiedRoute:
    AuthPlayerAuthGamesGameIdEmailVerifiedRoute,
  AuthPlayerAuthGamesGameIdResetPasswordRoute:
    AuthPlayerAuthGamesGameIdResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutAuthedRouteChildren {
  LayoutAuthedAccountRoute: typeof LayoutAuthedAccountRoute
  LayoutAuthedIndexRoute: typeof LayoutAuthedIndexRoute
  LayoutAuthedOrganizationsOrganizationIdRoute: typeof LayoutAuthedOrganizationsOrganizationIdRoute
  LayoutAuthedGamesIndexRoute: typeof LayoutAuthedGamesIndexRoute
  LayoutAuthedOrganizationsIndexRoute: typeof LayoutAuthedOrganizationsIndexRoute
  LayoutAuthedPlayersIndexRoute: typeof LayoutAuthedPlayersIndexRoute
  LayoutAuthedGamesGameIdIndexRoute: typeof LayoutAuthedGamesGameIdIndexRoute
  LayoutAuthedGamesGameIdPlayersPlayerIdRoute: typeof LayoutAuthedGamesGameIdPlayersPlayerIdRoute
  LayoutAuthedGamesGameIdPlayersIndexRoute: typeof LayoutAuthedGamesGameIdPlayersIndexRoute
}

const LayoutAuthedRouteChildren: LayoutAuthedRouteChildren = {
  LayoutAuthedAccountRoute: LayoutAuthedAccountRoute,
  LayoutAuthedIndexRoute: LayoutAuthedIndexRoute,
  LayoutAuthedOrganizationsOrganizationIdRoute:
    LayoutAuthedOrganizationsOrganizationIdRoute,
  LayoutAuthedGamesIndexRoute: LayoutAuthedGamesIndexRoute,
  LayoutAuthedOrganizationsIndexRoute: LayoutAuthedOrganizationsIndexRoute,
  LayoutAuthedPlayersIndexRoute: LayoutAuthedPlayersIndexRoute,
  LayoutAuthedGamesGameIdIndexRoute: LayoutAuthedGamesGameIdIndexRoute,
  LayoutAuthedGamesGameIdPlayersPlayerIdRoute:
    LayoutAuthedGamesGameIdPlayersPlayerIdRoute,
  LayoutAuthedGamesGameIdPlayersIndexRoute:
    LayoutAuthedGamesGameIdPlayersIndexRoute,
}

const LayoutAuthedRouteWithChildren = LayoutAuthedRoute._addFileChildren(
  LayoutAuthedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthedRoute: typeof LayoutAuthedRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthedRoute: LayoutAuthedRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserAvatarRoute: ApiUserAvatarRoute,
  ApiGamesGameIdLogoRoute: ApiGamesGameIdLogoRoute,
  ApiOrganizationsOrganizationIdLogoRoute:
    ApiOrganizationsOrganizationIdLogoRoute,
  ApiPlayerAuthGameIdSplatRoute: ApiPlayerAuthGameIdSplatRoute,
  ApiOrganizationsOrganizationIdUsersUserIdAvatarRoute:
    ApiOrganizationsOrganizationIdUsersUserIdAvatarRoute,
  ApiV1GamesGameIdAuthResendVerificationRoute:
    ApiV1GamesGameIdAuthResendVerificationRoute,
  ApiV1GamesGameIdAuthResetPasswordRoute:
    ApiV1GamesGameIdAuthResetPasswordRoute,
  ApiV1GamesGameIdPlayerChangeEmailRoute:
    ApiV1GamesGameIdPlayerChangeEmailRoute,
  ApiV1GamesGameIdPlayerSignOutRoute: ApiV1GamesGameIdPlayerSignOutRoute,
  ApiV1GamesGameIdPlayerIndexRoute: ApiV1GamesGameIdPlayerIndexRoute,
  ApiV1GamesGameIdAuthSignInAnonymouslyRoute:
    ApiV1GamesGameIdAuthSignInAnonymouslyRoute,
  ApiV1GamesGameIdAuthSignInEmailRoute: ApiV1GamesGameIdAuthSignInEmailRoute,
  ApiV1GamesGameIdAuthSignUpEmailRoute: ApiV1GamesGameIdAuthSignUpEmailRoute,
  ApiV1AdminGamesGameIdPlayersPlayerIdIndexRoute:
    ApiV1AdminGamesGameIdPlayersPlayerIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
